export const ERRORS = "ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_PRODUCT = "GET_PRODUCT";
export const PRODUCTS = "PRODUCTS";
export const SUCCESFUL_REGISTER = "SUCCESFUL_REGISTER";
export const FAILURE_REGISTER = "FAILURE_REGISTER";
export const AUTH_ERROR = "AUTH_ERROR";
